export const Reciepts = [
  {
    id: 1,
    image: [
      "https://foodish-api.com/images/biryani/biryani1.jpg",
      "https://foodish-api.com/images/biryani/biryani4.jpg",
      "https://foodish-api.com/images/biryani/biryani9.jpg",
    ],
    title: "Hyderabadi Biryani",
    description:
      "A fragrant rice dish cooked with marinated meat, saffron, and traditional spices.",
    price: 18,
    category: "biryani",
    rating: 4.8,
    ingredients: ["rice", "chicken", "yogurt", "saffron", "spices"],
    calories: 600,
    preparationTime: 40,
  },
  {
    id: 2,
    image: [
      "https://foodish-api.com/images/butter-chicken/butter-chicken1.jpg",
      "https://foodish-api.com/images/butter-chicken/butter-chicken4.jpg",
      "https://foodish-api.com/images/butter-chicken/butter-chicken11.jpg",
    ],
    title: "Butter Chicken",
    description:
      "A rich and creamy tomato-based curry made with tender chicken pieces.",
    price: 15,
    category: "butter-chicken",
    rating: 4.7,
    ingredients: ["chicken", "butter", "cream", "tomato", "spices"],
    calories: 450,
    preparationTime: 30,
  },
  {
    id: 3,
    image: [
      "https://foodish-api.com/images/dosa/dosa1.jpg",
      "https://foodish-api.com/images/dosa/dosa2.jpg",
      "https://foodish-api.com/images/dosa/dosa5.jpg",
    ],
    title: "Masala Dosa",
    description:
      "A crispy rice crepe filled with spiced mashed potatoes and served with chutney and sambar.",
    price: 10,
    category: "dosa",
    rating: 4.6,
    ingredients: ["rice", "lentils", "potatoes", "spices", "coconut chutney"],
    calories: 350,
    preparationTime: 20,
  },
  {
    id: 4,
    image: [
      "https://foodish-api.com/images/pasta/pasta1.jpg",
      "https://foodish-api.com/images/pasta/pasta2.jpg",
      "https://foodish-api.com/images/pasta/pasta4.jpg",
    ],
    title: "Penne Arrabbiata",
    description:
      "A spicy Italian pasta dish made with penne and a fiery tomato-based sauce.",
    price: 12,
    category: "pasta",
    rating: 4.5,
    ingredients: ["penne", "tomatoes", "garlic", "chili flakes", "olive oil"],
    calories: 400,
    preparationTime: 25,
  },
  {
    id: 5,
    image: [
      "https://foodish-api.com/images/rice/rice1.jpg",
      "https://foodish-api.com/images/rice/rice4.jpg",
      "https://foodish-api.com/images/rice/rice6.jpg",
    ],
    title: "Fried Rice",
    description:
      "A savory dish of stir-fried rice with vegetables, eggs, and soy sauce.",
    price: 8,
    category: "rice",
    rating: 4.4,
    ingredients: ["rice", "soy sauce", "vegetables", "eggs", "spices"],
    calories: 300,
    preparationTime: 15,
  },
  {
    id: 6,
    image: [
      "https://foodish-api.com/images/burger/burger4.jpg",
      "https://foodish-api.com/images/burger/burger2.jpg",
      "https://foodish-api.com/images/burger/burger5.jpg",
    ],
    title: "Classic Cheeseburger",
    description:
      "A juicy beef patty topped with cheese, lettuce, and tomato, served in a toasted bun.",
    price: 10,
    category: "burger",
    rating: 4.6,
    ingredients: ["beef", "cheese", "lettuce", "tomato", "bun"],
    calories: 500,
    preparationTime: 15,
  },
  {
    id: 7,
    image: [
      "https://foodish-api.com/images/dessert/dessert1.jpg",
      "https://foodish-api.com/images/dessert/dessert2.jpg",
      "https://foodish-api.com/images/dessert/dessert3.jpg",
    ],
    title: "Gulab Jamun",
    description:
      "Soft and spongy milk-based dumplings soaked in rose-flavored sugar syrup.",
    price: 5,
    category: "dessert",
    rating: 4.8,
    ingredients: ["milk powder", "sugar", "rose water", "ghee"],
    calories: 300,
    preparationTime: 10,
  },
  {
    id: 8,
    image: [
      "https://foodish-api.com/images/idly/idly1.jpg",
      "https://foodish-api.com/images/idly/idly2.jpg",
      "https://foodish-api.com/images/idly/idly3.jpg",
    ],
    title: "Steamed Idly",
    description:
      "Soft and fluffy steamed rice cakes served with sambar and coconut chutney.",
    price: 7,
    category: "idly",
    rating: 4.7,
    ingredients: ["rice", "lentils", "sambar", "coconut chutney"],
    calories: 150,
    preparationTime: 10,
  },
  {
    id: 9,
    image: [
      "https://foodish-api.com/images/pizza/pizza1.jpg",
      "https://foodish-api.com/images/pizza/pizza2.jpg",
      "https://foodish-api.com/images/pizza/pizza4.jpg",
    ],
    title: "Pepperoni Pizza",
    description:
      "A classic pizza topped with pepperoni slices, mozzarella, and marinara sauce.",
    price: 15,
    category: "pizza",
    rating: 4.9,
    ingredients: ["dough", "pepperoni", "mozzarella", "tomato sauce"],
    calories: 400,
    preparationTime: 20,
  },
  {
    id: 10,
    image: [
      "https://foodish-api.com/images/samosa/samosa1.jpg",
      "https://foodish-api.com/images/samosa/samosa7.jpg",
      "https://foodish-api.com/images/samosa/samosa3.jpg",
    ],
    title: "Vegetable Samosa",
    description:
      "Crispy deep-fried pastries stuffed with a spiced vegetable filling.",
    price: 5,
    category: "samosa",
    rating: 4.6,
    ingredients: ["flour", "potatoes", "peas", "spices", "oil"],
    calories: 250,
    preparationTime: 15,
  },
];
